### ISSUE TITLE
Wrong z-Index when using dialog framework in nested dialogs

### ISSUE THREAD

**Issue by Tosken1337** [adminfaces/admin-template#119]
##### Issue Overview

If the user will open a second model dialog from an open dialog using the Dialog Framework the z-index is wrong.

The modal overlay does not cover the first dialog.

The css definition of class
body .ui-dialog.ui-widget-content, body .ui-dialog 
sets an important flag on the z-index which overrides the dynamic one.

##### How to reproduce  
You can check the behavior on the showcase under UIElements -> Dialog -> Button "Dialog Framework"

EDIT
adding the screenshot:
![dialog-framework-z-index](https://user-images.githubusercontent.com/1592273/43995379-23ff27b4-9d83-11e8-8910-33f381fd9f77.png)

**Comment by rmpestano** [comment]
Hi @Tosken1337, 

yes, this is a known issue/limitation that I couldn't solve yet. I'll detail so maybe someone can investigate and come with a solution:

1 - We had to override PrimeFaces dialog z-index because Bootstrap sets a z-index of 1030 for nav-bar ([see here](https://github.com/adminfaces/admin-theme/blob/9c1abc65bcc2ad6ba96a6b52122dab0b0762845f/src/main/resources/less/admin-lte/bootstrap/variables.less#L277));  
2 - So we set dialog z-index value to be greater than navbar one ([see here](https://github.com/adminfaces/admin-theme/blob/9c1abc65bcc2ad6ba96a6b52122dab0b0762845f/src/main/resources/less/primefaces-admin/variables.less#L50));
3 - We needed to use `!important` flag because PrimeFaces sets dialog z-index via style attribute ([see here](https://github.com/adminfaces/admin-theme/blob/9c1abc65bcc2ad6ba96a6b52122dab0b0762845f/src/main/resources/less/primefaces-admin/components/dialog.less#L21)); 

So that's why all dialog framework have same z-index.

**Comment by rmpestano** [comment]
I've managed to fix by setting a css class to level2 and level3 dialogs and changing their z-index, [see this commit](https://github.com/adminfaces/admin-showcase/commit/847c77490d1cb1290cfdc3abf85952287e3e8469). 

![dlg-framework-fix](https://user-images.githubusercontent.com/1592273/43995639-12f3b8d6-9d88-11e8-8613-49c4be91a7b9.png)

**Comment by Tosken1337** [comment]
Thanks for this workaround

**Comment by lagar84** [comment]
I am sorry about commenting on a closed issue, but I also was affected by this bug. 
(Not in dialog framework, but simple nested modal dialogs).

I could workaround it by removing the custom z-index !important and lowering boostrap by 100 in variables.less:

<pre>
@zindex-navbar: 900;
@zindex-dropdown: 900;
@zindex-popover: 960;
@zindex-tooltip: 970;
@zindex-navbar-fixed: 930;
@zindex-modal-background: 940;
@zindex-modal: 950;
</pre>

(Primefaces has a tendency starting dialogs in 1000 - I am not sure but it is observable)

Could this be a solution, or you already tried and found other problems?

Keep up the good work.
Best wishes,

**Comment by rmpestano** [comment]
Hi @lagar84, can you provide a PR request with this fix? I actually don't remember If I've tried this.

Thank you in advance

**Comment by lagar84** [comment]
Yes, I will provide a PR (on admin-theme project). I made some tests on my project, it worked, but it is not a full test, since I do not use many boostrap components. adminlte layout worked fine, so far.

**Comment by lagar84** [comment]
PR: https://github.com/adminfaces/admin-theme/pull/219

**Comment by rmpestano** [comment]
A good test is admin-showcase project, it also have some automated functional tests [see here for running locally](https://github.com/adminfaces/admin-showcase/blob/master/README.adoc#testing) and also [this video](https://youtu.be/zZJOH0UUcJs) shows they running. If the tests passes is a good evidency that your PR doesn't introduce side effects/bugs.

**Comment by rmpestano** [comment]
I'll take a look and test the PR as soon as possible, thank you!
