### ISSUE TITLE
Skins does not change Primefaces components colors.

### ISSUE THREAD

**Issue by mnesarco** [adminfaces/admin-template#146]
##### Issue Overview

I have tested all skins: navbar and menu colors are set by the skin, but links, buttons, table headers, panels, etc remain the same: bluesy. 

##### Current Behaviour

Skin does not affect primefaces components colors.

##### Expected Behaviour

Skins should set colors for everything.

##### Additional Information

* AdminFaces version:  1.0.0.RC19
* PrimeFaces version: 6.2
* JSF implementation: 2.3

**Comment by rmpestano** [comment]
Hi @mnesarco,

sorry for the delayed reply.

For now this behavior is "by design", it is how it works on admin-lte, [see here](https://adminlte.io/themes/AdminLTE/pages/UI/buttons.html). However this is quite possible to implement but we would need to discuss how every component would work, for example how `btn-primary` should look like on `skin-red`? and btn-danger? both would be red?

IN terms of implementation it is quite easy to change the colors based on the skin because the skin name is on the body of the page...
