### ISSUE TITLE
Warning about p:autoUpdate being deprecated

### ISSUE THREAD

**Issue by torgre** [adminfaces/admin-template#48]
##### Issue Overview

Since the PrimeFaces Update to Version 6.2 the `autoUpdate` attributes of components are deprecated. The new tag `<p:autoUpdate>` should be used.

##### Current Behaviour

Annoying warnings in the logs on each partial update:

```
INFO  [org.primefaces.component.messages.MessagesRenderer] (default task-50) autoUpdate attribute is deprecated and will be removed in a future version, use p:autoUpdate component instead.
```

##### Expected Behaviour

Correct usage of `<p:autoUpdate>` tag without info message.

##### How to reproduce  

Fire any kind of partial update to the page, resulting in the `<p:messages>` tag inside `admin.xhtml` or `admin-top.xhtml` being executed.

A sample project or code may help. Can it be reproduced in [admin-starter](https://github.com/adminfaces/admin-starter)?

##### Additional Information

* Affected version: 1.0.0.RC13-SNAPSHOT

**Comment by rmpestano** [comment]
Hi @torgre,

I saw that change, the main problem is that this template works with older PrimeFaces versions. Last time I tested it worked even with PF 5.x but pretty sure it works with 6.0 and 6.1. 

The problem is that auto update doesn't exists on those versions. 

For now I woundn't change that, I think we should wait until PrimeFaces remove the autoUpdate attribute. For the logging issue you can change your logging level to WARN or ERROR on the class `org.primefaces.component.messages.MessagesRenderer`.

What do you think?

**Comment by torgre** [comment]
Yeah you are right, I did not think about backwards compatibility :thinking:

Makes sense to include support for older PrimeFaces versions for version 1.0.0. 

The log statement was also already removed by commit https://github.com/primefaces/primefaces/commit/2bf184d8dafe28b63e0e73fe3ce1da88397d1fc8 about two weeks ago, so when using latest `master` from PrimeFaces it is already gone :smile:

**Comment by rmpestano** [comment]
:+1:
